<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Otter.Torrent\Otter.Torrent.csproj" />
    <ProjectReference Include="..\Otter.Tracker\Otter.Tracker.csproj" />
    <ProjectReference Include="..\Otter.Peer\Otter.Peer.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
